### ISSUE TITLE
team abfrage ohne das der user ein team hat

### ISSUE THREAD

**Issue by Feier68** [gigaclub/BuilderSystemAPI#26]
```
[27.03 15:13:46.345] INFO: [Lobby-1] [15:13:46 ERROR]: Could not pass event PlayerJoinEvent to Builder_System_Plugin v${project.version}
[27.03 15:13:46.345] INFO: [Lobby-1] java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.util.Map (java.lang.Boolean and java.util.Map are in module java.base of loader 'bootstrap')
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.gigaclub.buildersystem.BuilderSystem.getTeamNameByMember(BuilderSystem.java:240) ~[buildersystemplugin-1.18.2.1.0.0-all.jar:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.gigaclub.buildersystemplugin.listener.joinlistener.handlePlayerJoin(joinlistener.java:91) ~[buildersystemplugin-1.18.2.1.0.0-all.jar:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-265]
[27.03 15:13:46.345] INFO: [Lobby-1]    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kevinxdev** [comment]
@Feier68 please check if it's fixed after the Team Plugin is ready.

**Comment by kevinxdev** [comment]
Issue moved to [gigaclub/TeamAPI #3](https://github.com/gigaclub/TeamAPI/issues/3) via [**ZenHub**](https://www.zenhub.com/)
